### PR TITLE
Add REST API

### PR DESCRIPTION
**Pull request by tsuda7**
Adding the REST API to patriot-workflow-scheduler is underway, in order to manage its data from outside in a flexible way. (Thanks to @zenmyo 's support!)

Any advice would be appreciated, especially for the POST method to add a new job.

### CODE REVIEW

**Comment by tsuda7** [comment]
Modifications from the last comment:

- Put `protected` to all POST, PUT, DELETE methods
- Build jobs from a command

**Comment by zenmyo** [comment]
Can you add tests for the new API?
(e.g., https://github.com/CyberAgent/patriot-workflow-scheduler/blob/develop/spec/patriot/worker/info_server_spec.rb#L49)

**Comment by tsuda7** [comment]
Okay, I will be on it.
I also added a documentation for explaining the REST API.

**Comment by tsuda7** [comment]
Now adding tests has been done. I'll work on developing React's front pages and later ask for merging this branch.

**Comment by tsuda7** [comment]
Let me fix some typos before being merged

**Comment by tsuda7** [comment]
I'll fix the old api back to keep the response format the same before.

**Pull request closed without merging**
